name: Engine Watcher
on:
  workflow_dispatch:

jobs:
  check-engines:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug files
        run: |
          echo "WORKFLOW NEWTEST"
          pwd
          ls -la
          echo "---- watcher.py ----"
          cat watcher.py

      - name: Stop here
        run: |
          echo "SEE ON UUS WORKFLOW"
          exit 1
